#pragma once

/* Colors */
#define BACKGROUND_COLOR ANSI_BG_WHITE
#define GRID_COLOR ANSI_LIGHT_GRAY
#define NODE GRID_COLOR "┼" RESET
#define WALL_COLOR ANSI_BLACK

#define RESET ANSI_RESET BACKGROUND_COLOR

/* Grid */
#define HORIZONTAL_GRID GRID_COLOR "────" RESET
#define VERTICAL_GRID GRID_COLOR "│" RESET

/* DOUBLE_WALLS ------------------------------------------------------------- */
/* Walls */
#define HORIZONTAL_WALL_DOUBLE WALL_COLOR "════" RESET
#define VERTICAL_WALL_DOUBLE WALL_COLOR "║" RESET

/* Wall nodes */
#define NODE_MIDDLE_DOUBLE WALL_COLOR "╬" RESET
#define NODE_HORIZONTAL_DOUBLE WALL_COLOR "═" RESET
#define NODE_VERTICAL_DOUBLE WALL_COLOR "║" RESET

#define NODE_TOP_DOUBLE WALL_COLOR "╦" RESET
#define NODE_LEFT_DOUBLE WALL_COLOR "╠" RESET
#define NODE_RIGHT_DOUBLE WALL_COLOR "╣" RESET
#define NODE_BOTTOM_DOUBLE WALL_COLOR "╩" RESET

#define NODE_TOP_LEFT_DOUBLE WALL_COLOR "╔" RESET
#define NODE_TOP_RIGHT_DOUBLE WALL_COLOR "╗" RESET
#define NODE_BOTTOM_LEFT_DOUBLE WALL_COLOR "╚" RESET
#define NODE_BOTTOM_RIGHT_DOUBLE WALL_COLOR "╝" RESET

/* SIMPLE_WALLS ------------------------------------------------------------- */
/* Walls */
#define HORIZONTAL_WALL_SIMPLE WALL_COLOR "────" RESET
#define VERTICAL_WALL_SIMPLE WALL_COLOR "│" RESET

/* Wall nodes */
#define NODE_MIDDLE_SIMPLE WALL_COLOR "┼" RESET
#define NODE_HORIZONTAL_SIMPLE WALL_COLOR "─" RESET
#define NODE_VERTICAL_SIMPLE WALL_COLOR "│" RESET

#define NODE_TOP_SIMPLE WALL_COLOR "┬" RESET
#define NODE_LEFT_SIMPLE WALL_COLOR "├" RESET
#define NODE_RIGHT_SIMPLE WALL_COLOR "┤" RESET
#define NODE_BOTTOM_SIMPLE WALL_COLOR "┴" RESET

#define NODE_TOP_LEFT_SIMPLE WALL_COLOR "┌" RESET
#define NODE_TOP_RIGHT_SIMPLE WALL_COLOR "┐" RESET
#define NODE_BOTTOM_LEFT_SIMPLE WALL_COLOR "└" RESET
#define NODE_BOTTOM_RIGHT_SIMPLE WALL_COLOR "┘" RESET

#define EMPTY_FRAME RESET "    "
